completed modulepath rebuild list, modified README

diff --git a/zhwkpkg b/zhwkpkg
--- a/zhwkpkg
+++ b/zhwkpkg
@@ -2,32 +2,32 @@
 
 SOURCEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-echo Checking configuration correctness..
+echo "Checking configuration correctness.." 1>&2
 # are they exists?
 if ! [ -r $SOURCEDIR/serveraddr ]
 then
-echo Server address file \'serveraddr\' not exist or permission denied.
+echo "Server address file \'serveraddr\' not exist or permission denied." 1>&2
 exit 1
 fi
 if ! [ -r $SOURCEDIR/installpath ]
 then
-echo Install path file \'installpath\' not exist or permission denied.
+echo "Install path file \'installpath\' not exist or permission denied." 1>&2
 exit 1
 fi
 # is the content correct?
 curl $(cat $SOURCEDIR/serveraddr) 2>/dev/null 1>/dev/null
 if [ $? -gt 0 ] 
 then
-echo WARNING: Specified server is unreachable.
-echo          But you may continue.
+echo "WARNING: Specified server is unreachable." 1>&2
+echo "         But you may continue." 1>&2
 fi
 if ! [ -d $(cat $SOURCEDIR/installpath) ]
 then
-echo WARNING: Specified install path not exist. Creating..
+echo "WARNING: Specified install path not exist. Creating.." 1>&2
 mkdir -p $(cat $SOURCEDIR/installpath)
 if [ $? -gt 0 ]
 then
-    echo Unable to create the install folder.
+    echo "Unable to create the install folder." 1>&2
     exit 1
 fi
 fi
@@ -61,11 +61,8 @@ case "$1" in
     get)
     $SOURCEDIR/zhwkpkg-get.sh $2
     ;;
-    observe)
-    $SOURCEDIR/zhwkpkg-observe.sh $2
-    ;;
-    investigate)
-    $SOURCEDIR/zhwkpkg-observe $2 $3
+    modulepath)
+    $SOURCEDIR/zhwkpkg-modulepath.sh $2
     ;;
     *)
     echo "Invalid command. Please read the document for usage."
